name: latest-build
on:
  push:
    branches:
      - develop
jobs:
  docker-builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        geonode_version:
          - "3.0"
    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push GEP-GeoNode
        id: docker_build_geonode
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/docker/Dockerfile
          push: true
          tags: lucernae/gep_geonode:django-latest
          build-args: |
            GEONODE_VERSION=${{ matrix.geonode_version }}
      - name: Image digest
        run: echo ${{ steps.docker_build_geonode.outputs.digest }}

      - name: Build and push GEP-Frontend
        id: docker_build_gep_frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: lucernae/gep_frontend:kartoza-latest
      - name: Image digest
        run: echo ${{ steps.docker_build_gep_frontend.outputs.digest }}


      - name: Build and push GEP-Backend
        id: docker_build_gep_backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: lucernae/gep_backend:kartoza-latest
      - name: Image digest
        run: echo ${{ steps.docker_build_gep_backend.outputs.digest }}
